import {StyleSheet} from 'react-native';
export const baseStyle=StyleSheet.create({
   them:{
       backgroundColor:'#000543'//主题颜色
   },
   acyive:(focus)=>{//选中颜色
       if(focus)
       {
           return '#36a6e5'
       }
       return '#fff'
   },
    main:{
        backgroundColor:'#101d3d'
    },
   loginButton:{
       height:22,paddingTop:0,paddingBottom:0
   },
    marLeft10:{
       marginLeft:10
    },
    marLeft115:{
        marginLeft:15
    },
    marLeft20:{
        marginLeft:20
    },
    marRight10:{
       marginRight:10
    },
    marRight15:{
        marginRight:15
    },
    marRight20:{
        marginRight:20
    },
   domaiText:{
       height: 20,
       color:'#fff',
       textAlign:'center',
       backgroundColor:'#2b338a',
       lineHeight:20
   },
    greenColor:{
       color:'#0cff00'
    },
    colorYellow:{
       color:"#ffc900"
    },
    colorDanger:{
       color:'#f53d3d'
    },
    borderBlue:{
       borderColor:"#001579"
    },
    borderBottom:{
       borderBottomWidth:1,borderStyle:'solid'
    },
   mainBackground:{
       backgroundColor:'#101d3d'
   },
   loginContainer:{
       textAlign:'center',
       backgroundColor:'#101d3d',
       justifyContent:'center'
   },
   headerStyle:{
       backgroundColor:'#000543',
       color:'#fff',
       textAlign:'center'
   },
    colorWite:{
       color:'#fff',
    },
    menusItem:{
        borderColor:'#123079'
    },
    menusItemCon:{
        borderColor:'#123079',
        paddingRight:0
    },
    buttonSubymit:{
        backgroundColor: '#a56001', borderRadius: 5
    },
    activiNation:{//活动导航
       flex: 1,flexDirection:'row',justifyContent:'space-evenly',height:41,marginTop:10,alignItems:'center'
    },
    activiList:{
        borderWidth:1,height:180,borderStyle:'solid',alignItems:'center',borderColor:'#b37a00'
    },
    activiListSet:{
        flex:1,width:'100%',padding:5,flexDirection:'row',justifyContent:'space-between',paddingBottom:0
    },
    activiButton:{
       width:100,
        height:34,
        justifyContent:'center',
        paddingTop: 0,
        paddingBottom: 0
    },
    userInfo:{
        flex:1,
        alignItems:'center',
        justifyContent:'center',
        marginTop: 10
    },
    lockViptx:{
       color:'#ffa700',
       textAlign:'center',
       lineHeight:25
    },
    lockVipbt:{
       width:73,height:25,backgroundColor:'#ca9c00',justifyContent:'center',marginLeft:5
    },
    lockVipbttx:{
       color:'#fff',
       textAlign:'center'
    },
    vipMoneybt:{
       height:36,paddingTop:0,paddingBottom:0,justifyContent:'center',color:'#fff',alignItems:'center'
    },
    userInfoLink:{
       width:'33.333%',
        justifyContent:'center',alignItems:'center',marginBottom:40
    },
    userInfoLinkContain:{
       width:60,
        height:60
    },
    vipContain:{

    },
    vipListItem:{
       flex:1,flexDirection:'row',justifyContent:'space-between',alignItems:"center",height:52
    },
    vipListItemTxleft:{
        color:"#fff",marginLeft:20
    },
    vipclubBanner:{
     flex:1,
        width:'100%'
    }
});